steps:
- id: mvn-Build
  name: maven:3.3-jdk-8
  entrypoint: sh
  args:
  - -c
  - mvn package testing it
- id: Docker-build-push
  name: gcr.io/cloud-builders/docker
  entrypoint: bash
  args:
  - -c
  - |-
    docker build -t https://pigen-demo-tbzd7duvvq-ew.a.run.app .
    docker push https://pigen-demo-tbzd7duvvq-ew.a.run.app
options:
  logging: CLOUD_LOGGING_ONLY
